services:
  user_db:
    image: postgres:14.13-alpine3.20
    environment:
      POSTGRES_DB: lms_user_service
      POSTGRES_USER: mirodil
      POSTGRES_PASSWORD: 1212
    volumes:
      - postgres_data_user:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mirodil -d lms_user_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  finance_db:
    image: postgres:14.13-alpine3.20   
    environment:
      POSTGRES_DB: lms_finance_service
      POSTGRES_USER: mirodil
      POSTGRES_PASSWORD: 1212
    volumes:
      - postgres_data_finance:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mirodil -d lms_finance_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine3.20
    ports:
      - "6380:6379"


  go_user_service:
    build:
      context: ./user_service
    ports:
      - "8081:8081"
    depends_on:
      - user_db
      - redis
    environment:
      DATABASE_URL: postgres://mirodil:1212@user_db:5432/lms_user_service?sslmode=disable
      REDIS_URL: redis://redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default


  go_finance_service:
    build:
      context: ./finance_service
    ports:
      - "8082:8082"
    depends_on:
      - finance_db
      - redis
    environment:
      DATABASE_URL: postgres://mirodil:1212@finance_db:5432/lms_finance_service?sslmode=disable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - go_user_service
      - go_finance_service
    environment:
      USER_SERVICE_URL: http://go_user_service:8081
      FINANCE_SERVICE_URL: http://go_finance_service:8082
    networks:
      - default

volumes:
  postgres_data_user:
  postgres_data_finance:


networks:
  default:
    name: lms_default